language: node_js

node_js:
  - 8

env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1

script:
  - npm test

addons:
  apt:
    packages:
      - gcc-4.8
      - libstdc++6
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libudev-dev
